### ISSUE TITLE
.idea folder should not be under version control

### ISSUE THREAD

**Issue by spacegaier** [apromore/ApromoreCode#171]
The contents are IDE-dependent (IntelliJ IDEA). At least "_workspace.xml_" and the complete "_libraries_" folder should go.

Some references:

- https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems
- http://stackoverflow.com/a/26336926/1947205

**Comment by raboczi** [comment]
I went ahead and removed the particularly forbidden IDEA files (workspace.xml) and added them to .gitignore to prevent them from creeping back in.  I'll consult the IDE-using folk and see whether removing the .idea folders entirely will cause them any difficulty; I'd personally prefer they were entirely gone.

**Comment by spacegaier** [comment]
Solved with commit https://github.com/apromore/ApromoreCode/commit/7a2078d37f0c399a759b04dffbeefb3a16db362d
