### ISSUE TITLE
CSV conversion failure

### ISSUE THREAD

**Issue by verenich** [apromore/ApromoreCode#176]
https://github.com/apromore/ApromoreCode/blob/2dd5f9f0c3250e00e375178edcba486bcedc406c/Predictor-Training-Portal-Plugin/src/test/kotlin/cs/ut/ui/controllers/TrainingControllerUnitTest.kt#L71

this test keeps failing
```
Failed tests:
  TrainingControllerUnitTest.testWriteCSV:78 expected:<...""four""","five
six"[]
> but was:<...""four""","five
]ix"[
>
```

**Comment by raboczi** [comment]
My best guess would be that the test for what happens when there’s a newline character in a quoted CSV entry is picking up some kind of platform variation in newline handling.  What OS is running the test?

**Comment by verenich** [comment]
Windows 10, same for Windows Server 2016

**Comment by raboczi** [comment]
Yeah, that makes sense; Windows uses CR-LF as a newline, all the unixish OSes use CR.  That probably means \n was the mistake here, since it makes the test input vary by platform.  Maybe try replacing it with tests for both \r\f and \r instead?  I think this is a real bug the test has caught.

**Comment by verenich** [comment]
indeed, replacing \n with \r\n makes the test pass
